/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Calculator.java
 *
 * Created on 17 ส.ค. 2554, 12:15:58
 */
package sudoku;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Nantawat
 */
public class Calculator extends javax.swing.JFrame {

    /** Creates new form Calculator */
    JTextField txtInput = new JTextField();
    JPanel cPanel = new JPanel();
    JPanel lPanel = new JPanel();
    

    public Calculator() {
        initComponent();
        add(txtInput,BorderLayout.NORTH);
        cPanel.setLayout(new GridLayout(4,5));
        
        
         setSize(400,300);
        setVisible(true);
        setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }
    JButton b0,b1,b2,b3,b4,b5,b6,b7,b8,b9;
    JTextField bMC,bMR;
    
    private void initComponent(){
        b0 = new JButton("0");
        b1 = new JButton("1");
        b2 = new JButton("2");
        b3 = new JButton("3");
        b4 = new JButton("4");
        b5 = new JButton("5");
        b6 = new JButton("6");
        b7 = new JButton("7");
        b8 = new JButton("8");
        b9 = new JButton("9");
        bMC = new JTextField("MC");
        bMR = new JTextField("MR");
        cPanel.add(b7);
        cPanel.add(b8);
        cPanel.add(b9);
        cPanel.add(b4);
        cPanel.add(b5);
        cPanel.add(b6);
        cPanel.add(b1);
        cPanel.add(b2);
        cPanel.add(b3);
        
  lPanel.add(bMC);
  lPanel.add(bMR);
        
        
        add(cPanel);
        add(lPanel,BorderLayout.WEST);
        lPanel.setBackground(Color.red);
        lPanel.setLayout(new GridLayout(0,1));
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                new Calculator();
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

