/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableNine.java
 *
 * Created on 17 ส.ค. 2554, 13:24:43
 */
package sudoku;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Nantawat
 */
public class TableNine extends javax.swing.JFrame {
    
    JPanel mainPanel = new JPanel();
    JPanel subPanel = new JPanel();
    
    public TableNine() {
        initComponent();
        add(mainPanel,BorderLayout.CENTER);
        mainPanel.setLayout(new GridLayout(3,3));
        setSize(600,600);
        setVisible(true);
        setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    }
    JTextField a1,a2,a3,a4,a5,a6,a7,a8,a9;
    private void initComponent(){
        
        a1 = new JTextField("1");
        a2 = new JTextField("2");
        a3 = new JTextField("3");
        a4 = new JTextField("4");
        a5 = new JTextField("5");
        a6 = new JTextField("6");
        a7 = new JTextField("7");
        a8 = new JTextField("8");
        a9 = new JTextField("9");
        
        a1.setHorizontalAlignment(JTextField.CENTER);
        a2.setHorizontalAlignment(JTextField.CENTER);
        a3.setHorizontalAlignment(JTextField.CENTER);
        a4.setHorizontalAlignment(JTextField.CENTER);
        a5.setHorizontalAlignment(JTextField.CENTER);
        a6.setHorizontalAlignment(JTextField.CENTER);
        a7.setHorizontalAlignment(JTextField.CENTER);
        a8.setHorizontalAlignment(JTextField.CENTER);
        a9.setHorizontalAlignment(JTextField.CENTER);
        
        mainPanel.add(a1);
        mainPanel.add(a2);
        mainPanel.add(a3);
        mainPanel.add(a4);
        mainPanel.add(a5);
        mainPanel.add(a6);
        mainPanel.add(a7);
        mainPanel.add(a8);
        mainPanel.add(a9);
        
        add(mainPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TableNine();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
